version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    allow:
      # Framework gems
      - dependency-name: rspec
        dependency-type: direct
      - dependency-name: sinatra
        dependency-type: direct
