# Please insert new items alphabetically.
design-system-dev:
  members:
    - 36degrees
    - alex-ju
    - dashouse
    - hannalaakso
    - igloosi
    - nickcolley
    - timpaul

  channel:
    "#design-system-dev"

  exclude_titles:
    - DO NOT MERGE
    - WIP

govuk-data-informed:
  members:
    - chao-xian
    - kylemacpherson
    - matmoore
    - pmanrubia
    - theKHutDeveloper
    - tombye

  channel:
    "#govuk-data-informed"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - "Waiting on factcheck"
    - WIP

  use_labels: true

  exclude_labels:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - "Waiting on factcheck"

  quotes:
    - Be the change you want to see!
    - Help each other out. Pair if possible.
    - Be considerate to remote workers. Ask \#remote-workers for tips.
    - Who's organising the next team lunch?
    - If you're not well, don't come in to the office. And get some rest!
    - Does your work have a story? Has your story got points?
    - I AM VENGEANCE! I AM THE NIGHT! I AM BATMAN! :batsignal:

govuk-datagovuk-tech:
  members:
    - andrewgarner
    - benthorner
    - brucebolt
    - emmabeynon
    - hannako
    - maxgds
    - rossjones

  channel:
    "#govuk-datagovuk-tech"

  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  include_repos:
    - datagovuk_publish
    - datagovuk_find
    - datagovuk_infrastructure
    - datagovuk_ckan_deployment
    - ckanext-datagovuk

govuk-licensing:
  members:
    - PeteLeaman
    - SomniGiggles
    - steven-radford
    - chrispapto

  channel:
    "#govuk-licensing"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[WIP]"

govuk-platform-health:
  members:
    - barrucadu
    - bevanloon
    - binaryberry
    - deborahchua
    - elliotcm
    - hongoose
    - jonodrew
    - kevindew
    - steventux
    - thomasleese

  channel:
    "#govuk-platform-health"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "WIP"

govuk-porg-pages:
  members:
    - andysellick
    - Davidslv
    - MahmudH
    - rubenarakelyan
    - sihugh
    - tijmenb
    - vanitabarrett

  channel:
    "#govuk-porg-pages"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[Don't merge]"
    - "[SPIKE]"
    - "[WIP]"

govuk-tax-and-nav:
  members:
    - 1pretz1
    - alextea
    - cbaines
    - koetsier
    - leenagupte
    - miaallers
    - mmholland88
    - myst3ria
    - peteglondon
    - tijmenb
    - vanitabarrett

  channel:
    "#govuk-tax-and-nav"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - WIP
    - "[SEAL IGNORE]"
    - RFC

re-infra-internal:
  members:
    - afda16
    - dougneal
    - issyl0
    - rtrinque
    - schmie
    - stephengrier
    - stephenharker
    - suthagahrt
    - szd55gds

  channel:
    "#re-infra-internal"

  exclude_titles:
    - "[DO NOT MERGE]"
    - WIP

  quotes:
    - "Someone needs to think of some new quotes!"

testing:
  members:
    - binaryberry
    - boffbowsh

  channel:
    "#bot-testing"

  exclude_titles:
    - "[DO NOT MERGE]"
    - WIP

  quotes:
    - Everyone should have the opportunity to learn. Don’t be afraid to pick up stories on things you don’t understand and ask for help with them.
    - Be nice and respect each other. Support each other.
    - Don’t be a silo of knowledge
