# Please insert new items alphabetically.
digitalmarketplace:
  members:
    - alex9smith
    - phantas
    - domoscargin
    - bjgill
    - daniele-occhipinti
    - ghill95
    - ccs-jamie-e

  channel:
    "#dm-2ndline"

  exclude_titles:
    - WIP

  include_repos:
    - "digitalmarketplace-admin-frontend"
    - "digitalmarketplace-agreements"
    - "digitalmarketplace-antivirus-api"
    - "digitalmarketplace-api"
    - "digitalmarketplace-apiclient"
    - "digitalmarketplace-aws"
    - "digitalmarketplace-bad-words"
    - "digitalmarketplace-brief-responses-frontend"
    - "digitalmarketplace-briefs-frontend"
    - "digitalmarketplace-buyer-frontend"
    - "digitalmarketplace-content-loader"
    - "digitalmarketplace-contained"
    - "digitalmarketplace-credentials"
    - "digitalmarketplace-developer-tools"
    - "digitalmarketplace-docker-base"
    - "digitalmarketplace-frameworks"
    - "digitalmarketplace-frontend-toolkit"
    - "digitalmarketplace-functional-tests"
    - "digitalmarketplace-govuk-frontend"
    - "digitalmarketplace-jenkins"
    - "digitalmarketplace-logdia"
    - "digitalmarketplace-manual"
    - "digitalmarketplace-performance-testing"
    - "digitalmarketplace-router"
    - "digitalmarketplace-runner"
    - "digitalmarketplace-scripts"
    - "digitalmarketplace-search-api"
    - "digitalmarketplace-supplier-frontend"
    - "digitalmarketplace-test-utils"
    - "digitalmarketplace-user-frontend"
    - "digitalmarketplace-utils"
    - "digitalmarketplace-visual-regression"
    - "govuk-frontend-jinja"

  compact: false

digitalmarketplace-team:
  channel:
    "#dm-frameworks"

  quotes:
    - "We feel comfortable asking and answering questions from each other - no matter how basic"
    - "We help each other grow and learn"
    - "We are supportive and look out for each other"
    - "We value each other's roles and contributions"
    - "We are inclusive and considerate to others"
    - "We communicate in an inclusive and effective manner"
    - "We ensure meetings are focused with a clear purpose and relevant people, and keep to time"
    - "We have meetings that are effective, short and have outcomes"
    - "We respect each other's working styles and patterns"
    - "We have a good life-work balance"
    - "We are remote-first"
    - "We are flexible"
    - "We acknowledge people may be struggling and not able to be as productive as in normal times"
    - "We are good at protecting our time as a team"
    - "We do the hard work to make it easier on others"
    - "We make time for learning and development"
    - "We put users first"
    - "We are ambitious but realistic"
    - "We are open, honest and transparent"
    - "We make evidence-based decisions"
    - "We take the time to think things through"
    - "We are open to new ideas, perspectives and methods"
    - "We are empowered to speak up"
    - "We remember the prime directive"

govuk-accessibility-team:
  members:
    - maxgds
    - owenatgov
    - chris-gds
    - edwardkerry

  channel:
    "#govuk-accessibility-team"

  compact: true

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[PROTOTYPE]"
    - WIP
    - "[WIP]"

govuk-accounts:
  channel:
    "#govuk-accounts"

  quotes:
    - "We put users first. We strive to create services that bring real value to our users and that meet their needs and expectations."
    - "We believe users should feel safe and confident when they use our services."
    - "We design for everyone. We think about under-represented audiences from the start and check our biases throughout the design process."
    - "We’re comfortable challenging assumptions and asking difficult questions. We speak truth to power."
    - "We’re OK with change, failure, ambiguity, and adapting our approach."
    - "We work collaboratively. Our work does not happen in discipline silos and we value the contributions of every discipline equally."
    - "We treat each other with integrity, honesty and respect."
    - "We work in the open so users and government colleagues know what we’re doing and why."
    - "We know we can't do this alone. We need to work with teams across GDS and government to succeed."
    - "We invest time and effort in increasing our understanding of the problems we’re working on. This will help us make things better for users and move the conversation about personalisation in government forward."

govuk-accounts-tech:
  members:
    - barrucadu
    - bevanloon
    - danacotoran
    - huwd

  channel:
    "#govuk-accounts-tech"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[PROTOTYPE]"
    - WIP
    - "[WIP]"

govuk-brexit-content-team:
  members:
    - benthorner
    - sihugh

  channel:
    "#govuk-brexit-content-team"

  compact: true

  exclude_titles:
    - "[PROTOTYPE]"
    - WIP
    - "[WIP]"

govuk-corona-products:
  members:
    - gclssvglx
    - GDSNewt
    - JonathanHallam
    - kevindew
    - leenagupte
    - Rosa-Fox

  channel:
    "#govuk-corona-services-tech"

  exclude_titles:
    - "DO NOT MERGE"
    - "🚧"
    - "[WIP]"
    - "[Do Not Merge]"

govuk-data-labs:
  members:
    - ESKYoung
    - exfalsoquodlibet
    - mammykins
    - maxf
    - nacnudus
    - oscarwyatt
    - st-alice
    - suganya-s
    - VitalieMogoreanu
    - ZacharyForrest
    - zilnhoj

  channel:
    "#govuk-data-labs"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[PROTOTYPE]"
    - WIP
    - "[WIP]"

  use_labels: true

  exclude_labels:
    - "wip"
    - "WIP"
    - "ignore"

  quotes:
    - "Be Excellent To Each Other!"
    - ":smiling-batman:"
    - "Don't be working if you're ill!"
    - ":green_heart:"
    - "Remember to take into consideration that our colleagues may be having a hard time outside of work. Support them at a team and individual level."
    - "Remember to avoid talking over each other during meetings, and be mindful of colleagues who wish to speak but have yet to do so."
    - "Understand the diverse character types within our team and appreciate that some of us may prefer a description of a meeting in advance to allow time to prepare."
    - "Keep conversations inclusive to the audience, ensuring that technical detail is fairly high level where possible."
    - "Be mindful of the workload of others even if it does not impact yours directly."
    - "Clarify the importance of attendance in certain meetings, outlining the purpose/objective, and where appropriate an agenda that helps us get to said outcome."
    - "Give informal and continuous feedback especially if the feedback includes encouragement."
    - "We're not 'working from home', we are _'working at home during a crisis_', so we need to take the time that we need during a working day."


govuk-datagovuk:
  members:
    - kentsanggds

  channel:
    "#govuk-datagovuk"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[PROTOTYPE]"
    - WIP
    - "[WIP]"

govuk-explore-navigation:
  members:
    - chao-xian
    - DilwoarH
    - injms

  channel:
    "#govuk-explore-navigation"

  exclude_titles:
    - "[DO NOT MERGE]"
    - WIP
    - "[WIP]"

  quotes:
    - "Be Excellent To Each Other!"
    - ":smiling-batman:"
    - "Don't be working if you're ill!"
    - ":green_heart:"
    - "We're not 'working from home', we are _'working at home during a crisis_', so take that time to look after yourselves even during a working day."

govuk-platform-health:
  members:
    - 1pretz1
    - beccapearce
    - benjamineskola
    - brucebolt
    - callumknights
    - ChrisBAshton
    - deborahchua
    - hannako
    - kentsanggds
    - MuriloDalRi
    - nicholsj
    - Tetrino

  channel:
    "#govuk-platform-health"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "WIP"

  quotes:
    - Be ready and willing to pair on work
    - Slack as primary point of contact; email for things you want to remember
    - Assume everyone is trying to do the right thing
    - Look out for each other
    - Make sure every meeting has a purpose and objective and explains who is required
    - Keep stand up updates as short as possible
    - Make sure anyone who wants to be involved in a decision has the opportunity to be
    - Try with each bit of work to upskill others
    - It's okay to spend some time understanding the thing(s) before implementing the solution
    - It's OK to pick up and work on something you don't understand yet

  compact: true

govuk-pay:
  members:
    - alexbishop1
    - antoniasimmons
    - crispinfugds
    - danworth
    - dasarindra
    - dj-maisy
    - gidsg
    - heathd
    - iqbalgds
    - jabrahoarder
    - jfharden
    - katstevens
    - kbottla
    - mrlumbu
    - niaaudrina
    - nimalank7
    - oswaldquek
    - richblake
    - samanthabry
    - SandorArpa
    - sfount
    - stephencdaly
    - xander-gds
    - sjzarb

  channel:
    "#govuk-pay-tech"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[DRAFT]"
    - WIP

govuk-replatforming:
  members:
    - bilbof
    - deanwilson
    - issyl0
    - MahmudH
    - richardTowers
    - seb-szy

  channel:
    "#govuk-replatforming"

  exclude_titles:
    - "[DO NOT MERGE]"
    - WIP
    - "[WIP]"

govwifi:
  members:
    - colinbm
    - koetsier
    - camdesgov
    - sarahseewhy
    - seb-szy
    - cbaines
    - szd55gds
    - jimnarey

  include_repos:
    - govwifi-acceptance-tests
    - govwifi-admin
    - govwifi-authentication-api
    - govwifi-build
    - govwifi-builder-task
    - govwifi-concourse-deploy-pipeline
    - govwifi-concourse-runner
    - govwifi-dashboard
    - govwifi-database-backup
    - govwifi-dev-docs
    - govwifi-frontend
    - govwifi-logging-api
    - govwifi-product-page
    - govwifi-redirect
    - govwifi-safe-restarter
    - govwifi-shared-frontend
    - govwifi-smoke-tests
    - govwifi-tech-docs
    - govwifi-terraform
    - govwifi-user-signup-api
    - govwifi-watchdog

  channel:
    "#govwifi-monitoring"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[PROTOTYPE]"
    - WIP
    - "[WIP]"
    - "[PARKED]"
