# Please insert new items alphabetically.
design-system-dev:
  members:
    - aliuk2012
    - amyhupe
    - dashouse
    - hannalaakso
    - joelanman
    - nickcolley
    - 36degrees
    - timpaul

  channel:
    "#design-system-dev"

  exclude_titles:
    - DO NOT MERGE
    - WIP

digitalmarketplace:
  members:
    - benvand
    - lfdebrux
    - risicle
    - agalamatis
    - katstevens

  channel:
    "#dm-review"

  exclude_titles:
    - WIP

  compact: false

govuk-cookies:
  members:
    - vanitabarrett
    - chao-xian

  channel:
    "#govuk-cookie-policy"

  compact: true

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[PROTOTYPE]"
    - WIP
    - "[WIP]"

govuk-searchandnav:
  members:
    - andysellick
    - barrucadu
    - bilbof
    - injms
    - hannako
    - karlbaker02
    - koetsier
    - SamJamCul
    - sihugh
    - VitalieMogoreanu

  channel:
    "#govuk-searchandnav"

  compact: true

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[PROTOTYPE]"
    - WIP
    - "[WIP]"

govuk-pub-workflow:
  members:
    - 1pretz1
    - alex-ju
    - benthorner
    - brucebolt
    - emmabeynon
    - JonathanHallam
    - kevindew
    - Tetrino
    - theseanything

  channel:
    "#govuk-pubworkflow-dev"

  exclude_titles:
    - "DO NOT MERGE"
    - "WIP"

govuk-licensing:
  members:
    - PeteLeaman
    - SomniGiggles
    - steven-radford
    - chrispapto

  channel:
    "#govuk-licensing"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[WIP]"

govuk-platform-health:
  members:
    - AlanGabbianelli
    - bevanloon
    - callumknights
    - deborahchua
    - edwardkerry
    - elliotcm
    - hongoose
    - kentsanggds
    - MuriloDalRi
    - rubenarakelyan
    - thomasleese

  channel:
    "#govuk-platform-health"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "WIP"

  quotes:
    - Fika is a work-free environment
    - Spot improvement opportunities, be brave in announcing them
    - It's OK to work on something you don't understand yet
    - Knowledge sharing helps the team achieve its goals
    - "Before moving on to the next thing: pause, help out, deliver work as a team"
    - Work at a considered / sustainable pace
    - "Be aware of everyone's preferences on ways of working (team 'manual for me': https://drive.google.com/drive/u/0/folders/17TltBwRV0di0aAvQjUhQy4PutExL303q)"
    - Support remote working as the norm
    - Stay home if you're sick and don't pressure yourself to work from home
    - Slack as primary point of contact; email for things you want to remember
    - Support each other - ask questions, understand each other's point of view, and don't be afraid to ask for/offer help!

  compact: true

govuk-pay:
  members:
    - heathd
    - alexbishop1
    - cobainc0
    - danworth
    - heathd
    - jonheslop
    - kbottla
    - mrlumbu
    - oswaldquek
    - SandorArpa
    - stephencdaly
    - jankowiakmaria
    - sfount
    - RoryMalcolm
    
  channel:
    "#govuk-pay-tech"

  exclude_titles:
    - "[DO NOT MERGE]"
    - WIP

govuk-step-by-step:
  members:
    - AgaDufrat
    - ChrisBAshton
    - DilwoarH
    - erino
    - leenagupte
    - VitalieMogoreanu

  channel:
    "#govuk-step-by-step"

  compact: true

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[PROTOTYPE]"
    - WIP
    - "[WIP]"
