# Please insert new items alphabetically.
design-system-dev:
  members:
    - 36degrees
    - dashouse
    - hannalaakso
    - igloosi
    - nickcolley
    - timpaul

  channel:
    "#design-system-dev"

  exclude_titles:
    - DO NOT MERGE
    - WIP

govuk-pub-workflow:
  members:
    - alex-ju
    - benthorner
    - davbo
    - emmabeynon
    - erino
    - kevindew
    - tijmenb

  channel:
    "#govuk-pub-workflow"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - "DON'T MERGE"
    - "DO NOT MERGE"
    - "WIP"

govuk-data-informed:
  members:
    - chao-xian
    - kylemacpherson
    - maxgds
    - peteglondon
    - pmanrubia
    - theKHutDeveloper

  channel:
    "#govuk-data-informed"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - WIP

  use_labels: true

  exclude_labels:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE

  quotes:
    - Be the change you want to see!
    - Be Excellent To Each Other!
    - Be considerate to remote workers. Ask \#remote-workers for tips.
    - If you're not well, don't come in to the office. And get some rest!
    - I AM VENGEANCE! I AM THE NIGHT! I AM BATMAN! :batsignal:

govuk-datagovuk-tech:
  members:
    - andrewgarner
    - brucebolt
    - hannako
    - rossjones

  channel:
    "#govuk-datagovuk-tech"

  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  include_repos:
    - datagovuk_publish
    - datagovuk_find
    - datagovuk_infrastructure
    - datagovuk_ckan_deployment
    - ckanext-datagovuk
    - ckanext-s3-resources

govuk-licensing:
  members:
    - PeteLeaman
    - SomniGiggles
    - steven-radford
    - chrispapto

  channel:
    "#govuk-licensing"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[WIP]"

govuk-platform-health:
  members:
    - barrucadu
    - bevanloon
    - binaryberry
    - boffbowsh
    - brucebolt
    - deborahchua
    - elliotcm
    - hongoose
    - rubenarakelyan
    - steventux
    - thomasleese

  channel:
    "#govuk-platform-health"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "WIP"

govuk-content-pages:
  members:
    - andrewgarner
    - MahmudH
    - sihugh
    - vanitabarrett

  channel:
    "#govuk-content-pages"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[Don't merge]"
    - "[SPIKE]"
    - "[WIP]"

govuk-single-taxonomy:
  members:
    - 1pretz1
    - cbaines
    - koetsier

  channel:
    "#govuk-taxonomy"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - WIP
    - "[SEAL IGNORE]"
    - RFC

govuk-step-by-step:
  members:
    - leenagupte
    - andysellick
    - dilwoarh
    - jonodrew

  channel:
    "#govuk-step-by-step"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "DO NOT MERGE"
    - "Don't merge"
    - "[WIP]"
    - "WIP"

re-infra-internal:
  members:
    - afda16
    - dougneal
    - issyl0
    - rtrinque
    - schmie
    - stephengrier
    - stephenharker
    - suthagahrt
    - szd55gds

  channel:
    "#re-infra-internal"

  exclude_titles:
    - "[DO NOT MERGE]"
    - WIP

  quotes:
    - "Someone needs to think of some new quotes!"

re-tools-internal:
  members:
    - danielroseman
    - DavidJeche
    - ejrowley
    - idavidmcdonald
    - JonathanHallam
    - kentsanggds
    - philandstuff
    - MuriloDalRi

  channel:
    "#re-tools-internal"

  exclude_titles:
    - "[DO NOT MERGE]"
    - WIP

testing:
  members:
    - binaryberry
    - boffbowsh

  channel:
    "#bot-testing"

  exclude_titles:
    - "[DO NOT MERGE]"
    - WIP

  quotes:
    - Everyone should have the opportunity to learn. Don’t be afraid to pick up stories on things you don’t understand and ask for help with them.
    - Be nice and respect each other. Support each other.
    - Don’t be a silo of knowledge
