# Please insert new items alphabetically.
design-system-dev:
  members:
    - aliuk2012
    - amyhupe
    - dashouse
    - hannalaakso
    - joelanman
    - nickcolley
    - 36degrees
    - timpaul

  channel:
    "#design-system-dev"

  exclude_titles:
    - DO NOT MERGE
    - WIP

digitalmarketplace:
  members:
    - benvand
    - lfdebrux
    - risicle
    - agalamatis
    - katstevens
    - jonodrew

  channel:
    "#dm-review"

  exclude_titles:
    - WIP

  compact: false

govuk-frontend-a11y:
  members:
    - chao-xian
    - vanitabarrett
    - injms
    - maxgds

  channel:
    "#govuk-frontend-a11y"

  compact: true

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[PROTOTYPE]"
    - WIP
    - "[WIP]"

  quotes:
    - "Be Excellent To Each Other!"
    - ":smiling-batman:"
    - "Don't be working if you're ill!"

govuk-searchandnav:
  members:
    - andysellick
    - barrucadu
    - bilbof
    - injms
    - hannako
    - karlbaker02
    - koetsier
    - SamJamCul
    - sihugh
    - VitalieMogoreanu

  channel:
    "#govuk-searchandnav"

  compact: true

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[PROTOTYPE]"
    - WIP
    - "[WIP]"

govuk-taxonomy:
  members:
    - oscarwyatt
    - koetsier

  channel:
    "#govuk-taxonomy"

  compact: true

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[PROTOTYPE]"
    - WIP
    - "[WIP]"

govuk-pub-workflow:
  members:
    - 1pretz1
    - alex-ju
    - benthorner
    - brucebolt
    - emmabeynon
    - JonathanHallam
    - kevindew
    - Tetrino
    - theseanything

  channel:
    "#govuk-pubworkflow-dev"

  exclude_titles:
    - "DO NOT MERGE"
    - "WIP"

govuk-licensing:
  members:
    - PeteLeaman
    - SomniGiggles
    - steven-radford
    - chrispapto

  channel:
    "#govuk-licensing"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[WIP]"

govuk-platform-health:
  members:
    - AlanGabbianelli
    - bevanloon
    - callumknights
    - cbaines
    - deborahchua
    - edwardkerry
    - kentsanggds
    - MahmudH
    - MuriloDalRi
    - rubenarakelyan
    - thomasleese

  channel:
    "#govuk-platform-health"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "WIP"

  quotes:
    - Be ready and willing to pair on work
    - Support remote working as a default
    - Stay home if you're sick and don't pressure yourself to work from home
    - Slack as primary point of contact; email for things you want to remember
    - Assume everyone is trying to do the right thing
    - Look out for each other
    - Make sure every meeting has a purpose and objective and explains who is required
    - Keep stand up updates as short as possible
    - Make sure anyone who wants to be involved in a decision has the opportunity to be
    - Try with each bit of work to upskill others
    - It's okay to spend some time understanding the thing(s) before implementing the solution
    - It's OK to pick up and work on something you don't understand yet

  compact: true

govuk-pay:
  members:
    - heathd
    - alexbishop1
    - cobainc0
    - danworth
    - heathd
    - jonheslop
    - kbottla
    - mrlumbu
    - oswaldquek
    - SandorArpa
    - stephencdaly
    - jankowiakmaria
    - sfount
    - RoryMalcolm

  channel:
    "#govuk-pay-tech"

  exclude_titles:
    - "[DO NOT MERGE]"
    - WIP

govuk-step-by-step:
  members:
    - AgaDufrat
    - ChrisBAshton
    - DilwoarH
    - erino
    - leenagupte
    - VitalieMogoreanu

  channel:
    "#govuk-step-by-step"

  compact: true

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[PROTOTYPE]"
    - WIP
    - "[WIP]"

  exclude_repos:
    - "gds-way"
