name: "Afternoon Seal"

on:
  workflow_dispatch: {}
  schedule:
    - cron:  '00 12 * * 1-5' # Runs at 12:00, Monday through Friday.

env:
  SEAL_ORGANISATION: alphagov
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  afternoon-seal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Afternoon Seal
        id: afternoon_seal
        run: |
          teams=(
            govuk-accounts
            govuk-platform-security-reliability
          )
          
          for team in ${teams[*]} ; do
            ./bin/seal_runner.rb $team quotes
          done
