name: "Dependapanda"

on:
  workflow_dispatch: {}
  schedule:
    - cron:  '00 9 * * 1-5' # Runs at 9:00 UTC, Monday through Friday.

env:
  SEAL_ORGANISATION: alphagov
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  dependapanda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Dependapanda
        id: dependapanda
        run: |
          ./bin/seal_runner.rb dependapanda
