name: "Morning Seal Quotes"

on:
  workflow_dispatch: {}
  schedule:
    - cron:  '30 7 * * 1-5' # Runs at 7:30 UTC, Monday through Friday.

env:
  SEAL_ORGANISATION: alphagov
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  morning-seal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Morning Seal Quotes
        id: morning_seal_quotes
        run: |
          ./bin/seal_runner.rb morning_seal_quotes
