name: "Morning Seal"

on:
  workflow_dispatch: {}
  schedule:
    - cron:  '30 7 * * 1-5' # Runs at 7:30, Monday through Friday.

env:
  SEAL_ORGANISATION: alphagov
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  morning-seal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Morning Seal
        id: morning_seal
        run: |
          teams=(
            di-authentication
            govuk-datagovuk
            govuk-developers
            govuk-forms
            govuk-pay
            govuk-platform-security-reliability
            govuk-publishing-access-and-permissions
            govuk-publishing-components
            govuk-publishing-experience
            govuk-publishing-mainstream-experience
            govuk-publishing-platform
            govuk-platform-engineering
            govwifi
            content-interactions-on-platform-govuk
            navigation-and-homepage-govuk
            ai-govuk
          )

          for team in ${teams[*]}; do
            ./bin/seal_runner.rb $team
          done

          morning_quote_teams=(
            fun-workstream-govuk
            fun-workstream-gds-community
            govuk-green-team
            navigation-and-homepage-govuk
            dev-platform-team
            ai-govuk
          )

          for team in ${morning_quote_teams[*]}; do
            ./bin/seal_runner.rb $team quotes
          done
