name: Run Tests
on: [push, pull_request]
jobs:

  codeql-sast:
    name: CodeQL SAST scan
    uses: alphagov/govuk-infrastructure/.github/workflows/codeql-analysis.yml@main
    permissions:
      security-events: write
      
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
    - name: Install dependencies and run Rake
      run: |
        bundle install
        bundle exec rake
